### ISSUE TITLE
上传图片不显示

### ISSUE THREAD

**Issue by heavy-metal** [GiantGo/giantgo-render#10]
有空白高度，但没渲染

**Comment by heavy-metal** [comment]
F12元素查看：
<div class="form-item" style="width: 100%; padding-left: 0px; padding-right: 0px;"><upload-image-render items="" options="[object Object]" model-value="" path="root.upload_image_NAPyToAc"></upload-image-render></div>

**Comment by heavy-metal** [comment]
F12元素查看`<div class="form-item" style="width: 100%; padding-left: 0px; padding-right: 0px;"><upload-image-render items="" options="[object Object]" model-value="" path="root.upload_image_NAPyToAc"></upload-image-render></div>`

**Comment by spx443812507** [comment]
可以在[JSFiddle](https://jsfiddle.net/iamkun/ods20k7t/4) 或 [CodePen](https://codepen.io/iamkun/pen/YzWMaVr)复现一下么

**Comment by heavy-metal** [comment]
之前有代码冲突解决了，现在出现了新的问题，表单校验失效，输入文字仍提示未输入，reset()和submit()无法使用

**Comment by spx443812507** [comment]
还是在线复现一下吧，光说文字实在无法理解是什么情况

**Comment by heavy-metal** [comment]
这是截图
https://img2.imgtp.com/2024/05/15/skHtNjwp.png
https://img2.imgtp.com/2024/05/15/Z8s99irm.png
https://img2.imgtp.com/2024/05/15/EhaduX9g.png

**Comment by heavy-metal** [comment]
可以弄一个QQ群吗？

**Comment by spx443812507** [comment]
https://giantgo.github.io/giantgo-render/example/
在预览地址上可以复现吗

**Comment by heavy-metal** [comment]
预览地址复现不了，但只要你创建一个新的Vue3 ts 项目，npm方式引入，form-render去渲染都会有这个问题，我试了好几次了

**Comment by spx443812507** [comment]
你可以加我qq，443812507，我现在定位到2.3.0可以，2.3.1就不行了

**Comment by spx443812507** [comment]
我把依赖的element-plus升级到了2.7.3，发布了新版就没问题了，你可以试一下
