### ISSUE TITLE
适配深色模式

### ISSUE THREAD

**Issue by Angela-zm** [GiantGo/giantgo-render#11]
我现在系统适配了深色模式，但引入组件后，发现组件未适配深色模式，导致页面展示效果很差，大佬有时间可以适配一下吗
![Uploading image.png…]()

**Comment by Angela-zm** [comment]
![image](https://github.com/user-attachments/assets/75a50183-b8d9-402d-8aca-e3aa878b9e75)

**Comment by spx443812507** [comment]
![image](https://github.com/user-attachments/assets/9ba9eb1c-2583-44f7-9cea-791cad3292f3)
[https://giantgo.github.io/giantgo-render/example/](url)
增加上深色模式支持了

**Comment by Angela-zm** [comment]
那我npm引入该怎么使用

**Comment by spx443812507** [comment]
giantgo-render更新到1.4.6版本就行了

**Comment by spx443812507** [comment]
可以参考源码里example文件夹里的代码

**Comment by Angela-zm** [comment]
好的  谢谢
