### ISSUE TITLE
大佬这个项目还在维护吗？

### ISSUE THREAD

**Issue by faruzanCN** [GiantGo/giantgo-render#4]
目前使用一堆elementplus报错，似乎是版本问题，本人新手暂时还不会看你的源码修改，或者大佬您能写一下二次开发文档吗？能暴露更多接口就更好了，比如能自定义组件

**Comment by spx443812507** [comment]
还在维护，最近家里有些事情没有跟进版本，我更新一下

**Comment by faruzanCN** [comment]
> 还在维护，最近家里有些事情没有跟进版本，我更新一下

大佬辛苦了
